name: Update README with Word Cloud

on:
  push:
    paths:
      - 'wordcloud_generator.py'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.13'

      - name: Install dependencies
        run: pip install wordcloud matplotlib bs4

      - name: Generate Word Cloud
        run: python wordcloud_generator.py

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md wordcloud.png
          git commit -m "Update README with word cloud"
          git push
